services:
  us-east:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-east
    hostname: us-east
    volumes:
      - node1:/cockroach/cockroach-data
      - ../certs:/cockroach/certs
    command:
      [
        "start",
        "--certs-dir=/cockroach/certs",
        "--store=/cockroach/cockroach-data",
        "--max-sql-memory=512MiB",
        "--cache=512MiB",
        "--listen-addr=us-east:26257",
        "--http-addr=0.0.0.0:8080",
        "--join=us-east:26257,us-central:26257,us-west:26257",
        "--locality=region=us-east,zone=east"
      ]
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - dcp-net

  us-central:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-central
    hostname: us-central
    volumes:
      - node2:/cockroach/cockroach-data
      - ../certs:/cockroach/certs
    command:
      [
        "start",
        "--certs-dir=/cockroach/certs",
        "--store=/cockroach/cockroach-data",
        "--max-sql-memory=512MiB",
        "--cache=512MiB",
        "--listen-addr=us-central:26257",
        "--http-addr=0.0.0.0:8080",
        "--join=us-east:26257,us-central:26257,us-west:26257",
        "--locality=region=us-central,zone=central"
      ]
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - dcp-net

  us-west:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: us-west
    hostname: us-west
    volumes:
      - node3:/cockroach/cockroach-data
      - ../certs:/cockroach/certs
    command:
      [
        "start",
        "--certs-dir=/cockroach/certs",
        "--store=/cockroach/cockroach-data",
        "--max-sql-memory=512MiB",
        "--cache=512MiB",
        "--listen-addr=us-west:26257",
        "--http-addr=0.0.0.0:8080",
        "--join=us-east:26257,us-central:26257,us-west:26257",
        "--locality=region=us-west,zone=west"
      ]
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - dcp-net

  init:
    image: cockroachdb/cockroach:${CRDB_VERSION}
    platform: linux/arm64
    container_name: init
    depends_on:
      - us-east
      - us-central
      - us-west
    volumes:
      - ../certs:/cockroach/certs
    command:
      [
        "init",
        "--certs-dir=/cockroach/certs",
        "--host=us-east:26257"
      ]
    networks:
      - dcp-net

volumes:
  node1:
  node2:
  node3:

networks:
  dcp-net:
    external: true
